In [ ]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
def prepare_data(df,forecast_col,forecast_out,test_size):
    label = df[forecast_col].shift(-forecast_out) #creating new column called label with the last 5 rows are nan
    X = np.array(df[[forecast_col]]) #creating the feature array
    X = preprocessing.scale(X) #processing the feature array
    X_lately = X[-forecast_out:] #creating the column i want to use later in the predicting method
    X = X[:-forecast_out] # X that will contain the training and testing
    label.dropna(inplace=True) #dropping na values
    y = np.array(label)  # assigning Y
    X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=test_size, random_state=0) #cross validation

    response = [X_train,X_test , Y_train, Y_test , X_lately]
    return response

In [ ]:
df = pd.read_csv("TSLA.csv")

In [ ]:
df

,Date,Open,High,Low,close,Adj Close,Volume
0,16/08/2016,45.098000,45.438000,44.681999,44.722000,44.722000,11335500
1,17/08/2016,44.866001,44.966000,44.560001,44.647999,44.647999,8935500
2,18/08/2016,44.764000,45.132000,44.458000,44.702000,44.702000,8572500
3,19/08/2016,44.708000,45.034000,44.506001,45.000000,45.000000,8297500
4,22/08/2016,44.834000,45.021999,44.535999,44.585999,44.585999,10327500
...,...,...,...,...,...,...,...
1253,09/08/2021,710.169983,719.030029,705.130005,713.760010,713.760010,14715300
1254,10/08/2021,713.989990,716.590027,701.880005,709.989990,709.989990,13432300
1255,11/08/2021,712.710022,715.179993,704.210022,707.820007,707.820007,9800600
1256,12/08/2021,706.340027,722.799988,699.400024,722.250000,722.250000,17459100
1257,13/08/2021,723.710022,729.900024,714.340027,717.169983,717.169983,16698900

In [ ]:
forecast_col = 'close'
forecast_out = 5
test_size = 0.2

In [ ]:
X_train, X_test, Y_train, Y_test , X_lately =prepare_data(df,forecast_col,forecast_out,test_size); #calling the method were the cross validation and data preperation is in
learner = LinearRegression() #initializing linear regression model

learner.fit(X_train,Y_train) #training the linear regression model

LinearRegression()

In [ ]:
score=learner.score(X_test,Y_test)#testing the linear regression model
forecast= learner.predict(X_lately) #set that will contain the forecasted data
response={}#creting json object
response['test_score']=score
response['forecast_set']=forecast

print(response)

{'test_score': 0.9898695355865649, 'forecast_set': array([718.99805051, 715.2088524 , 713.02783068, 727.53122914,
       722.42537006])}